version: '3.8'

services:
  couchdb:
    image: couchdb:3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=secret
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATA_COUCHDB_URI=http://admin:secret@couchdb:5984
    depends_on:
      - couchdb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  couchdb_data: