spring:
  application:
    name:
      knowledge
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:

# spring security配置 (空、DEBUG、TRACE)
logging:
  level:
    org:
      springframework:
        security:
          TRACE